import ApplicationLogo from '@/Components/ApplicationLogo';
import { Link, usePage } from '@inertiajs/react';

export default function GuestLayout({ children, maxWidth = 'max-w-sm lg:w-96' }) {
    const appSettings = usePage().props.appSettings || {};

    return (
        <div className="flex min-h-screen bg-bg">
            {/* Left Panel - Branding (Hidden on mobile) */}
            <div className="hidden lg:flex lg:w-1/2 flex-col justify-between bg-navy p-12 relative overflow-hidden">
                {/* Background image generated by AI */}
                <img src="/images/login-bg.jpg" alt="Capolista Production System" className="absolute inset-0 w-full h-full object-cover opacity-60 mix-blend-overlay" />
                
                {/* Dark gradient overlay so text remains readable */}
                <div className="absolute inset-0 bg-gradient-to-t from-navy/95 via-navy/50 to-navy/30 z-0"></div>

                <div className="relative z-10">
                    <Link href="/" className="inline-flex items-center gap-3">
                        {appSettings.company_logo ? (
                            <img src={`/storage/${appSettings.company_logo}`} alt={appSettings.company_name} className="h-10 w-auto object-contain" />
                        ) : (
                            <ApplicationLogo className="h-10 w-10 text-white" />
                        )}
                        <span className="text-[28px] font-oswald font-bold tracking-wider text-white">
                            {appSettings.company_name || 'CAPOLISTA APPAREL'}
                        </span>
                    </Link>
                </div>
                
                <div className="relative z-10 mb-12">
                    <h1 className="text-[42px] font-oswald font-bold text-white mb-4 leading-tight">
                        Sistem Manajemen <br /> Order & Produksi
                    </h1>
                    <p className="text-white/80 font-sans text-[15px] max-w-md leading-relaxed">
                        Pantau progres desain, printing, dan pemasangan dalam satu platform terintegrasi.
                    </p>
                </div>
            </div>

            {/* Right Panel - Form */}
            <div className="flex flex-1 flex-col justify-center px-4 py-12 sm:px-6 lg:flex-none lg:w-1/2 lg:px-20 xl:px-24 bg-bg">
                <div className={`mx-auto w-full ${maxWidth}`}>
                    <div className="lg:hidden mb-8 text-center">
                        <Link href="/" className="inline-flex flex-col items-center gap-2">
                            {appSettings.company_logo ? (
                                <img src={`/storage/${appSettings.company_logo}`} alt={appSettings.company_name} className="h-16 w-auto object-contain" />
                            ) : (
                                <div className="h-16 w-16 bg-navy rounded-xl flex items-center justify-center shadow-lg">
                                    <ApplicationLogo className="h-10 w-10 text-white" />
                                </div>
                            )}
                            <span className="text-[24px] font-oswald font-bold tracking-wider text-ink">{appSettings.company_name || 'CAPOLISTA APPAREL'}</span>
                        </Link>
                    </div>
                    {children}
                </div>
            </div>
        </div>
    );
}
